# Generated by Django 5.2 on 2025-04-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prodid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('prodname', models.CharField(max_length=20)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
